<?php

declare(strict_types=1);

namespace Aurora\Api\Tests\Unit;

use Aurora\Api\JsonApiResource;
use Aurora\Api\ResourceSerializer;
use Aurora\Api\Tests\Fixtures\TestEntity;
use Aurora\Entity\EntityType;
use Aurora\Entity\EntityTypeManager;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Symfony\Component\EventDispatcher\EventDispatcher;

#[CoversClass(ResourceSerializer::class)]
final class ResourceSerializerTest extends TestCase
{
    private EntityTypeManager $entityTypeManager;
    private ResourceSerializer $serializer;

    protected function setUp(): void
    {
        $this->entityTypeManager = new EntityTypeManager(new EventDispatcher());
        $this->entityTypeManager->registerEntityType(new EntityType(
            id: 'article',
            label: 'Article',
            class: TestEntity::class,
            keys: [
                'id' => 'id',
                'uuid' => 'uuid',
                'label' => 'title',
                'bundle' => 'type',
            ],
        ));

        $this->serializer = new ResourceSerializer($this->entityTypeManager);
    }

    #[Test]
    public function serializeEntityToResource(): void
    {
        $entity = new TestEntity([
            'id' => 42,
            'uuid' => 'abc-123-def',
            'title' => 'My Article',
            'type' => 'blog',
            'body' => 'Content here.',
        ]);

        $resource = $this->serializer->serialize($entity);

        $this->assertInstanceOf(JsonApiResource::class, $resource);
        $this->assertSame('article', $resource->type);
        $this->assertSame('abc-123-def', $resource->id);
    }

    #[Test]
    public function serializeExcludesIdAndUuidFromAttributes(): void
    {
        $entity = new TestEntity([
            'id' => 42,
            'uuid' => 'abc-123-def',
            'title' => 'My Article',
            'type' => 'blog',
            'body' => 'Content here.',
        ]);

        $resource = $this->serializer->serialize($entity);

        // id and uuid should NOT be in attributes.
        $this->assertArrayNotHasKey('id', $resource->attributes);
        $this->assertArrayNotHasKey('uuid', $resource->attributes);

        // Other fields should be in attributes.
        $this->assertSame('My Article', $resource->attributes['title']);
        $this->assertSame('blog', $resource->attributes['type']);
        $this->assertSame('Content here.', $resource->attributes['body']);
    }

    #[Test]
    public function serializeGeneratesSelfLink(): void
    {
        $entity = new TestEntity([
            'id' => 42,
            'uuid' => 'abc-123-def',
            'title' => 'Test',
        ]);

        $resource = $this->serializer->serialize($entity);

        $this->assertSame('/api/article/abc-123-def', $resource->links['self']);
    }

    #[Test]
    public function serializeUsesUuidAsResourceId(): void
    {
        $entity = new TestEntity([
            'id' => 42,
            'uuid' => 'some-uuid-value',
            'title' => 'Test',
        ]);

        $resource = $this->serializer->serialize($entity);

        $this->assertSame('some-uuid-value', $resource->id);
    }

    #[Test]
    public function serializeCollection(): void
    {
        $entities = [
            new TestEntity(['id' => 1, 'uuid' => 'uuid-1', 'title' => 'First']),
            new TestEntity(['id' => 2, 'uuid' => 'uuid-2', 'title' => 'Second']),
            new TestEntity(['id' => 3, 'uuid' => 'uuid-3', 'title' => 'Third']),
        ];

        $resources = $this->serializer->serializeCollection($entities);

        $this->assertCount(3, $resources);
        $this->assertContainsOnlyInstancesOf(JsonApiResource::class, $resources);
        $this->assertSame('uuid-1', $resources[0]->id);
        $this->assertSame('uuid-2', $resources[1]->id);
        $this->assertSame('uuid-3', $resources[2]->id);
    }

    #[Test]
    public function serializeEmptyCollection(): void
    {
        $resources = $this->serializer->serializeCollection([]);

        $this->assertSame([], $resources);
    }

    #[Test]
    public function serializeWithCustomBasePath(): void
    {
        $serializer = new ResourceSerializer($this->entityTypeManager, '/jsonapi');

        $entity = new TestEntity([
            'id' => 1,
            'uuid' => 'uuid-custom',
            'title' => 'Test',
        ]);

        $resource = $serializer->serialize($entity);

        $this->assertSame('/jsonapi/article/uuid-custom', $resource->links['self']);
    }

    #[Test]
    public function serializeEntityWithoutExplicitUuidUsesAutoGenerated(): void
    {
        $entity = new TestEntity([
            'id' => 1,
            'title' => 'No Explicit UUID',
        ]);

        $resource = $this->serializer->serialize($entity);

        // UUID should be auto-generated by EntityBase.
        $this->assertNotEmpty($resource->id);
        $this->assertSame($entity->uuid(), $resource->id);
    }
}
